fix bug causing double // in aws_iam_policy_document
trussworks/terraform-aws-health-notifications pull request #7
Opened 2021-05-13 20:35 UTC by jsarnovsky

The "/" in SSMAllowRead is causing the SSM permission to 400 auth error out due to invalid resource in permission by creating a double "//" while the actual ssm:GetParameter call is correct. 

arn:aws:ssm:us-west-2:0000000000:parameter//some/paremter/url
instead of 
arn:aws:ssm:us-west-2:0000000000:parameter/some/paremter/url

2021-07-15 22:44 UTC, dynamike commented
@jsarnovsky are you still looking to get this merged?

2021-09-28 20:18 UTC, jsarnovsky commented
Just saw this. I am still looking to have this merged.

2021-09-28 20:24 UTC, jsclarridge approved these changes

2021-09-28 20:31 UTC, jsclarridge requested changes
I initially approved it, but now I'm not clear if this change is needed. One option to avoid the double slash (//) is to not include the leading slash in the input parameter value.

2021-11-10 19:22 UTC, jsarnovsky commented
@jsclarridge I was revisiting this during the PR cleanup meeting. If I recall correctly, when we were getting the data source for aws_ssm_parameter, the url in AWS already has the slash in front of it. I know we tried removing it, and the url broke or terraform had a fir or something.

2021-11-10 19:39 UTC, jsclarridge commented
@jsarnovsky We don't have any terratests for this module, but it'd be helpful to test this change for two scenarios: where`ssm_slack_webhook_url` starts with `/` and where it doesn't. We may need conditional logic to trim the leading `/`, if present, when updating the IAM policy.

2022-10-26 14:48 UTC, rpdelaney commented
I'm closing this as stale. Please re-open if you still need it :)

2022-10-26 14:48 UTC, closed without merging